### ISSUE TITLE
Note For Reviewer

### ISSUE THREAD

**Issue by SanaTameem** [SanaTameem/book-an-appointment-back-end#12]
- This is the link of our Final Capstone Project's Kanban Board :
  - https://github.com/users/SanaTameem/projects/15/views/1\

- We are a team of 4 members :
  - @SanaTameem 
  - @HafizMassamTabraizKhan
  - @melkamu12
  - @H-Ramalan
  
  
![Kanban 3](https://github.com/SanaTameem/book-an-appointment/assets/71990110/ae182955-ef54-4d24-84cb-8e6eb959b660)

![Kanban 2](https://github.com/SanaTameem/book-an-appointment/assets/71990110/aa286bdd-71b8-4b69-85c7-85321fa4f6c6)

![Kanban 1](https://github.com/SanaTameem/book-an-appointment/assets/71990110/dfe1c5cd-b409-456d-9413-182a60dff9c3)

**Comment by Meltrust** [comment]
Hi @SanaTameem,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have descriptions, assignees, and pointings according to spec✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
